name: CI

on: 
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      uses: actions/checkout@v2
    - name: Run a multi-line script
      uses: actions/setup-node@v1
    - name: Instal dependencies
      run: |
        npm i
        npm i -g bower gulp
        bower install
    - name: Build
      run: |
        gulp styles
        rm -rf libs
        sed -i 's/bower_components/libs/g' ./index.html
        mv bower_components libs
    - name: Replace text
      uses: lefherz/action-sed@master
      with:
        args: sed -i "s/bower_components/libs/g" ./index.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .
