name: CI

on: 
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      uses: actions/checkout@v2
    - name: Run a multi-line script
      uses: actions/setup-node@v1
    - name: Instal dependencies
      run: |
        npm i
        npm i -g bower gulp
        bower install
    - name: Build
      run: |
        gulp styles
        rm -rf libs
        mv bower_components libs
        mv index.html index.html.back
        sed -e 's/bower_components/libs/g' >> index.html
        rm -rf index.html.back
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .
